### ISSUE TITLE
fyi

### ISSUE THREAD

**Issue by JeffreySarnoff** [c42f/LinSpaces2.jl#1]
Hi Chris,

From JuliaGeometry, I noticed your LinSpaces2 and you are using errorfree transfomations.  I spent a year culling and refining errorfree arithmetic for Julia.  Please appropriate any of that which would be helpful.

[Errorfree Arithmetic](https://github.com/J-Sarnoff/ErrorFreeArith.jl)  
[Faster Directed Rounding using EFTs](https://github.com/J-Sarnoff/RoundFast.jl)

with regard, Jeffrey

**Comment by c42f** [comment]
Thanks Jeffrey, well spotted (considering the mess that this package is :-) )

Honestly, LinSpaces2 is a defunct half-baked package which I should probably just delete, from when I was trying to resolve https://github.com/JuliaLang/julia/issues/14420.  Eventually @timholy got in and heroically designed his way out of the problem, rather than my doomed approach of trying to fix the LinSpace we had in 0.5 :-)
